config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  devise_scope :user do
    get '/volunteer/:id', :to => 'users/registrations#new', :as => 'volunteer_to_drive_for_zone'
    get '/volunteer_to_drive/:id', to: redirect("/volunteer/%{id}")
    get '/volunteer_to_drive', :to => 'users/registrations#new', :as => 'volunteer_to_drive'
    get "/users/sign_out" => "devise/sessions#destroy", :as => :get_destroy_user_session
  end

  # https://blog.heroku.com/real_time_rails_implementing_websockets_in_rails_5_with_action_cable
  # NOTE: to re-enable you also need to uncomment ./channels in application.js,
  # and the code in /channels/messages.js
  # and the meta tag in application.html.haml
  # and lined in development.rb and production.rb
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'home#index'

  match '/confirm' => 'home#confirm', via: :get, as: :confirm
  match '/about' => 'home#about', via: :get, as: :about
  match '/code_of_conduct' => 'home#code_of_conduct', via: :get, as: :code_of_conduct
  match '/terms_of_service' => 'home#terms_of_service', via: :get, as: :terms_of_service
  match '/privacy' => 'home#privacy', via: :get, as: :privacy

  get 'dispatch/:ride_zone_id/ride/:ride_id/edit' => 'dispatch#edit_ride', as: 'dispatch_edit_ride'
  resources :dispatch, only: [:show] do
    member do
      get 'messages' => 'dispatch#messages'
      get 'ride_pane' => 'dispatch#ride_pane'
      get 'drivers' => 'dispatch#drivers'
      get 'rides' => 'dispatch#rides'
      get 'flyer' => 'dispatch#flyer'
      get 'map' => 'dispatch#map'
    end
  end

  resources :driving do
    collection do
      get 'demo' => 'driving#demo'
      get 'status' => 'driving#status'
      post 'location' => 'driving#update_location'
      post 'available' => 'driving#available'
      post 'unavailable' => 'driving#unavailable'
      post 'accept_ride' => 'driving#accept_ride'
      post 'unaccept_ride' => 'driving#unaccept_ride'
      post 'pickup_ride' => 'driving#pickup_ride'
      post 'complete_ride' => 'driving#complete_ride'
      post 'cancel_ride' => 'driving#cancel_ride'
      get 'waiting_rides' => 'driving#waiting_rides'
      get 'ridezone_stats' => 'driving#ridezone_stats'
    end
  end

  get 'ride/:ride_zone_id' => 'rides#new', as: 'get_a_ride'
  get 'get_a_ride/:ride_zone_id', to: redirect("/ride/%{ride_zone_id}")
  get 'conseguir_un_paseo/:ride_zone_id' => 'rides#new'

  resources :rides, only: [:create, :edit, :update]

  resources :users do
    get :confirm, on: :member
  end

  namespace :api do
    namespace :v1, path: '1' do
      post 'twilio/sms' => 'twilio#sms'
      post 'twilio/voice' => 'twilio#voice'
      get 'places/search' => 'places#search'

      resources :conversations, only: [:show, :update] do
        member do
          post 'messages' => 'conversations#create_message'
          post 'close' => 'conversations#close'
          post 'rides' => 'conversations#create_ride'
          post 'update_attribute' => 'conversations#update_attribute'
          post 'remove_help_needed' => 'conversations#remove_help_needed'
        end
      end

      resources :rides, only: [:update_attribute] do
        collection do
          if ENV['DTV_IS_WORKER'] == 'TRUE' || Rails.env.test?
            post 'confirm_scheduled' => 'rides#confirm_scheduled'
          end
        end
        member do
          post 'update_attribute' => 'rides#update_attribute'
        end
      end

      resources :ride_zones do
        member do
          post 'assign_ride' => 'ride_zones#assign_ride'
          get 'conversations' => 'ride_zones#conversations'
          post 'conversations' => 'ride_zones#create_conversation'
          get 'drivers' => 'ride_zones#drivers'
          get 'rides' => 'ride_zones#rides'
          post 'rides' => 'ride_zones#create_ride'
          post 'change_role'
        end
      end
    end
  end

  get '/admin', to: redirect('/admin/ride_zones')
  match '/admin/voters' => 'admin/users#voters', via: :get
  namespace :admin do
    resources :conversations, only: [:index, :show] do
      member do
        # get 'messages' => 'conversations#messages'
        # get 'ride_pane' => 'conversations#ride_pane'
        post 'close' => 'conversations#close'
        post 'blacklist_voter_phone' => 'conversations#blacklist_voter_phone'
        post 'unblacklist_voter_phone' => 'conversations#unblacklist_voter_phone'
      end
    end
    resources :drivers, only: [:index] do
      member do
        post 'toggle_available'
      end
    end
    resources :metrics, only: [:index]
    resources :rides
    
    resources :ride_zones, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      member do
        get 'drivers'
        post 'add_role'
        post 'change_role'
        delete 'remove_role'
      end
      resources :ride_uploads do
        member do
          get 'schedule'
        end
      end
    end
    
    resources :simulations, only: [:index] do
      collection do
        post 'start_new' => 'simulations#start_new'
        post 'clear_all_data' => 'simulations#clear_all_data'
      end
      member do
        post 'stop' => 'simulations#stop'
        delete 'delete' => 'simulations#delete'
      end
    end
    resource :site, only: [:show, :edit, :update]
    resources :users, only: [:show, :edit, :update, :index, :destroy] do
      member do
        post 'qa_clear' => 'users#qa_clear'
      end
    end
  end

end

app/controllers/admin/conversations_controller.rb
class Admin::ConversationsController < Admin::AdminApplicationController
  include AccessMethods
  
  skip_before_action :require_admin_privileges, only: [:blacklist_voter_phone, :unblacklist_voter_phone, :close] 
  before_action :set_conversation, only: [:show, :messages, :ride_pane, :update_attribute, :close, :blacklist_voter_phone, :unblacklist_voter_phone]

  # GET /admin/conversations
  def index
    page = params[:page] || 1
    per_page = params[:per_page] || 25
    @conversations = Conversation.all.paginate(page: page, per_page: per_page).order("created_at ASC")
  end

  # GET /admin/conversations/1
  def show
  end


  ## REQUIRE dispatch permissions on the ride zone the conversation is attached to before
  ## permitting use of close and blacklisting
  
  # POST /admin/conversations/1/close
  
  # user_signed_in?
  def close
    @ride_zone = @conversation.ride_zone
    
    if user_signed_in? && has_zone_dispatch?
      @conversation.close(current_user.name)
      flash[:notice] = "Conversation closed."
      redirect_back(fallback_location: root_path) and return
    else
      render file: "#{Rails.root}/public/404", status: :not_found
    end
  end

  # POST /admin/converations/1/blacklist_voter_phone
  def blacklist_voter_phone
    if user_signed_in? && has_zone_dispatch?
      @conversation.blacklist_voter_phone
      flash[:notice] = "Voter Phone Blacklisted."
      redirect_back(fallback_location: root_path) and return
    else
      render file: "#{Rails.root}/public/404", status: :not_found
    end
  end

  # POST /admin/converations/1/unblacklist_voter_phone
  def unblacklist_voter_phone
    if user_signed_in? && has_zone_dispatch?
      @conversation.unblacklist_voter_phone
      flash[:notice] = "Voter Phone No Longer Blacklisted."
      redirect_back(fallback_location: root_path) and return
    else
      render file: "#{Rails.root}/public/404", status: :not_found
    end
  end

  private
  def set_conversation
    @conversation = Conversation.find(params[:id])
  end
end

app/controllers/api/v1/conversations_controller.rb
module Api::V1
  class ConversationsController < Api::ApplicationController
    include ConversationParams
    include AccessMethods

    before_action :find_conversation
    before_action :require_conversation_access
    before_action :ensure_message, only: :create_message

    def show
      render json: {response: @conversation.api_json(true)}
    end

    def update
      # caller is passing name as part of conversation hash but we need
      # to make it safe for updating the user object
      user_params = params.require(:conversation).permit(:name)
      unless user_params[:name].blank?
        @conversation.user.update_attribute(:name, user_params[:name])
      end
      if @conversation.update(conversation_params)
        render json: {response: @conversation.reload.api_json(false)}
      else
        render json: {error: @conversation.errors}
      end
    end

    def update_attribute
      if(params.has_key?(:name) && params.has_key?(:value))

        if params[:name] == 'pickup_at'
          val = TimeZoneUtils.origin_time(params[:value], @conversation.ride_zone.time_zone)
        else
          val = params[:value]
        end
        new_status = %w(sms_created in_progress).include?(@conversation.status) ? 'help_needed' : @conversation.status
        if @conversation.update_attributes( params[:name] => val, status: new_status )
          render json: {response: @conversation.reload.api_json(false)}
        else
          render json: {error: @conversation.errors}
        end
      else
        render json: {error: 'missing params'}
      end
    end

    def remove_help_needed
      if @conversation.ride && @conversation.lifecycle == 'info_complete'
        @conversation.update_attributes(status: :ride_created)
        render json: {response: @conversation.reload.api_json(false)}
      else
        render json: {error: 'Conversation must have ride and be info complete'}, status: 400
      end
    end

    def create_message
      msg = @conversation.send_from_staff(params[:message][:body], Rails.configuration.twilio_timeout)
      if msg.is_a?(String)
        render json: {error: msg}, status: 500
      else
        render json: {response: {message: {sent_at: I18n.localize(msg.created_at, format: '%-m/%-d  %l:%M%P'), body: "#{msg.body}" }}}, status: 200
      end
    end

    def create_ride
      # if driver_id is present, make sure they can be added before doing anything
      driver = nil
      if params[:driver_id].present?
        if (driver = User.find_by_id(params[:driver_id])).nil?
          render json: {error: "Could not find driver"}, status: 500
          return
        end
      end

      ActiveRecord::Base.transaction do
        if ride = Ride.create_from_conversation(@conversation)
          ride.assign_driver( driver, true, true ) if driver
          @conversation.mark_info_completed(ride)
          @conversation.user.mark_info_completed
          render json: {response: ride.reload.api_json}
        else
          render json: {error: "Could not create Ride from Conversation"}, status: 500
        end
      end
    end

    # POST /admin/conversations/1/close
    def close
      @conversation.close(current_user.name)
      render json: {response: @conversation.reload.api_json}
    end

    private
    def find_conversation
      @conversation = Conversation.find_by_id(params[:id])
      render json: {error: 'Conversation not found'}, status: 404 unless @conversation
    end

    def ensure_message
      render json: {error: 'Missing message parameter'}, status: 400 if params[:message].try(:[], :body).blank?
    end
  end
end

app/views/admin/conversations/_messages.html.haml
-# USED in /admin/conversations/:id, not the dispatcher modal

.messages
  - @conversation.messages.order('created_at asc').each do |message|
    .message{style: "text-align: #{(message.sent_by == 'Voter') ? 'left' : 'right'}"}
      %code
        #{message.created_at.localtime.strftime('%l:%M%P')},
        = message.sent_by
      .msg-body
        = message.body

-# just to make the javascript below a little easier to read
- msg_count = pluralize( @conversation.messages.count, 'message' )

- close_button = j( link_to 'Archive', close_admin_conversation_path(@conversation), class: 'btn btn-default btn-xs', data: { confirm: 'Are you sure? Conversations normally close themselves, only use this for orphans, bad actors, etc.' }, method: :POST )

:javascript
  // now that we have the conversation object, populate the modal header
  $('#conv-modal-title').html( "#{@conversation.id} <span>#{@conversation.from_phone.phony_formatted(normalize: :US, spaces: '-')}</span>" );
  $('#archive-btn').html("<span style='font-weight: normal;'>#{close_button}</span>")
  $('#msg-count').html( "#{msg_count}" );

app/views/admin/conversations/_table.html.haml
// locals:
//   conversations - a Conversation collection
//   include_show - true/false display show control
%table.admin
  %thead
    %tr
      %th RideZone
      %th Voter #
      %th Zone #
      %th Status
      %th Lifecycle
      %th Pickup Time
      %th Ride
      %th
      - if include_show
        %th

  %tbody
    - conversations.each do |conversation|
      %tr
        - if conversation.ride_zone
          %td= link_to conversation.ride_zone.name, admin_ride_zone_path(conversation.ride_zone)
        - else
          %td None Set
        %td= conversation&.user&.phone_number&.phony_formatted(normalize: :US, spaces: '-')
        %td= conversation&.ride_zone&.phone_number&.phony_formatted(normalize: :US, spaces: '-')
        %td= conversation.status_str
        %td= conversation.lifecycle_str
        %td= conversation.pickup_at.nil? ? 'None Set' : conversation.pickup_at.localtime.strftime('%m/%d %l:%M%P')
        - if conversation.ride
          %td= link_to conversation.ride.name, admin_ride_path(conversation.ride)
        - else
          %td Not yet
        %td= link_to 'Close', close_admin_conversation_path(conversation), class: 'btn btn-warning btn-xs', data: { confirm: 'This will permanently close the conversation and ride and remove the rider from the pool.' }, method: :POST
        - if conversation.voter_phone_blacklisted?
          %td= link_to 'Unblacklist #', unblacklist_voter_phone_admin_conversation_path(conversation), class: 'btn btn-default btn-xs', data: { confirm: "Are you sure you want to unblacklist phone number #{conversation.from_phone}?" }, method: :POST
        - else
          %td= link_to 'Block this number', blacklist_voter_phone_admin_conversation_path(conversation), class: 'btn btn-danger btn-xs', data: { confirm: "Are you sure you want to permanently block this phone number, #{conversation.from_phone}?" }, method: :POST


        - if include_show
          %td= link_to 'Show', admin_conversation_path(conversation)

-# if conversations.present? && include_show
  %nav{'aria-label': 'pagination'}
    = will_paginate conversations

app/views/admin/conversations/index.html.haml
:css
  #user-filter { margin: 0 0 20px 0;}
  #user-search { display: inline;}
  td { font-size: 14px; }

= render 'admin/nav', {active: 'conversations'}

%h1
  Conversations

= render partial: 'admin/conversations/table', locals: {conversations: @conversations, include_show: true}

app/views/admin/conversations/show.html.haml
:css
  h4, h6 { margin-top: 30px; }

%h4
  Conversation #{@conversation.id}
= render partial: 'admin/conversations/table', locals: {conversations: [@conversation], include_show: false}

%h4
  Messages

= render partial: 'messages'