config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  devise_scope :user do
    get '/volunteer/:id', :to => 'users/registrations#new', :as => 'volunteer_to_drive_for_zone'
    get '/volunteer_to_drive/:id', to: redirect("/volunteer/%{id}")
    get '/volunteer_to_drive', :to => 'users/registrations#new', :as => 'volunteer_to_drive'
    get "/users/sign_out" => "devise/sessions#destroy", :as => :get_destroy_user_session
  end

  # https://blog.heroku.com/real_time_rails_implementing_websockets_in_rails_5_with_action_cable
  # NOTE: to re-enable you also need to uncomment ./channels in application.js,
  # and the code in /channels/messages.js
  # and the meta tag in application.html.haml
  # and lined in development.rb and production.rb
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'home#index'

  match '/confirm' => 'home#confirm', via: :get, as: :confirm
  match '/about' => 'home#about', via: :get, as: :about
  match '/code_of_conduct' => 'home#code_of_conduct', via: :get, as: :code_of_conduct
  match '/terms_of_service' => 'home#terms_of_service', via: :get, as: :terms_of_service
  match '/privacy' => 'home#privacy', via: :get, as: :privacy

  get 'dispatch/:ride_zone_id/ride/:ride_id/edit' => 'dispatch#edit_ride', as: 'dispatch_edit_ride'
  resources :dispatch, only: [:show] do
    member do
      get 'messages' => 'dispatch#messages'
      get 'ride_pane' => 'dispatch#ride_pane'
      get 'drivers' => 'dispatch#drivers'
      get 'rides' => 'dispatch#rides'
      get 'flyer' => 'dispatch#flyer'
      get 'map' => 'dispatch#map'
    end
  end

  resources :driving do
    collection do
      get 'demo' => 'driving#demo'
      get 'status' => 'driving#status'
      post 'location' => 'driving#update_location'
      post 'available' => 'driving#available'
      post 'unavailable' => 'driving#unavailable'
      post 'accept_ride' => 'driving#accept_ride'
      post 'unaccept_ride' => 'driving#unaccept_ride'
      post 'pickup_ride' => 'driving#pickup_ride'
      post 'complete_ride' => 'driving#complete_ride'
      post 'cancel_ride' => 'driving#cancel_ride'
      get 'waiting_rides' => 'driving#waiting_rides'
      get 'ridezone_stats' => 'driving#ridezone_stats'
    end
  end

  get 'ride/:ride_zone_id' => 'rides#new', as: 'get_a_ride'
  get 'get_a_ride/:ride_zone_id', to: redirect("/ride/%{ride_zone_id}")
  get 'conseguir_un_paseo/:ride_zone_id' => 'rides#new'

  resources :rides, only: [:create, :edit, :update]

  resources :users do
    get :confirm, on: :member
  end

  namespace :api do
    namespace :v1, path: '1' do
      post 'twilio/sms' => 'twilio#sms'
      post 'twilio/voice' => 'twilio#voice'
      get 'places/search' => 'places#search'

      resources :conversations, only: [:show, :update] do
        member do
          post 'messages' => 'conversations#create_message'
          post 'close' => 'conversations#close'
          post 'rides' => 'conversations#create_ride'
          post 'update_attribute' => 'conversations#update_attribute'
          post 'remove_help_needed' => 'conversations#remove_help_needed'
        end
      end

      resources :rides, only: [:update_attribute] do
        collection do
          if ENV['DTV_IS_WORKER'] == 'TRUE' || Rails.env.test?
            post 'confirm_scheduled' => 'rides#confirm_scheduled'
          end
        end
        member do
          post 'update_attribute' => 'rides#update_attribute'
        end
      end

      resources :ride_zones do
        member do
          post 'assign_ride' => 'ride_zones#assign_ride'
          get 'conversations' => 'ride_zones#conversations'
          post 'conversations' => 'ride_zones#create_conversation'
          get 'drivers' => 'ride_zones#drivers'
          get 'rides' => 'ride_zones#rides'
          post 'rides' => 'ride_zones#create_ride'
          post 'change_role'
        end
      end
    end
  end

  get '/admin', to: redirect('/admin/ride_zones')
  match '/admin/voters' => 'admin/users#voters', via: :get
  namespace :admin do
    resources :conversations, only: [:index, :show] do
      member do
        # get 'messages' => 'conversations#messages'
        # get 'ride_pane' => 'conversations#ride_pane'
        post 'close' => 'conversations#close'
        post 'blacklist_voter_phone' => 'conversations#blacklist_voter_phone'
        post 'unblacklist_voter_phone' => 'conversations#unblacklist_voter_phone'
      end
    end
    resources :drivers, only: [:index] do
      member do
        post 'toggle_available'
      end
    end
    resources :metrics, only: [:index]
    resources :rides
    
    resources :ride_zones, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      member do
        get 'drivers'
        post 'add_role'
        post 'change_role'
        delete 'remove_role'
      end
      resources :ride_uploads do
        member do
          get 'schedule'
        end
      end
    end
    
    resources :simulations, only: [:index] do
      collection do
        post 'start_new' => 'simulations#start_new'
        post 'clear_all_data' => 'simulations#clear_all_data'
      end
      member do
        post 'stop' => 'simulations#stop'
        delete 'delete' => 'simulations#delete'
      end
    end
    resource :site, only: [:show, :edit, :update]
    resources :users, only: [:show, :edit, :update, :index, :destroy] do
      member do
        post 'qa_clear' => 'users#qa_clear'
      end
    end
  end

end

app/models/ride_upload.rb
class RideUpload < ApplicationRecord
  ALLOWED_MIME_TYPES = ['text/csv']
  
  before_validation :compute_csv_hash
  
  has_one_attached :csv
  
  belongs_to :user
  belongs_to :ride_zone
  has_many :potential_rides, -> { order 'id ASC' }
  
  enum status: [ :pending, :queued, :complete, :complete_with_failures, :failed ]
  
  validates :user, presence: true
  validates :ride_zone, presence: true
  validates :csv, presence: true
  validates :status, presence: true
  validates :name, uniqueness: true
  validates_uniqueness_of :csv_hash, on: :create, allow_blank: true, message: ': This file has already been uploaded.'
  validate :csv_must_be_correct_content_type
  
  def failed_potential_rides
    PotentialRide.where(ride_upload: self, status: :failed)
  end
  
  # TODO: more validations:
  # validate :has_correct_columns
  
  private
  
  def compute_csv_hash
    self.csv_hash = Digest::MD5.hexdigest(self.csv.download) if self.csv.attached?
  end
  
  def csv_must_be_correct_content_type
    if csv.attached? && !csv.blob.content_type.in?(ALLOWED_MIME_TYPES)
      errors.add(:csv, "Must be a CSV file")
    end
  end
  
end

app/controllers/admin/ride_uploads_controller.rb
class Admin::RideUploadsController < Admin::AdminApplicationController
  before_action :set_ride_upload, only: [:show, :edit, :update, :schedule, :destroy]
  before_action :set_ride_zone, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  # GET /ride_uploads
  def index
    @ride_uploads = RideUpload.where( ride_zone_id: @ride_zone.id )
  end

  # GET /admin/ride_zones/ca-25/ride_uploads/
  def show
    @failed_potential_rides = @ride_upload.failed_potential_rides
  end

  # GET /admin/ride_zones/ca-25/ride_uploads/new
  def new
    @ride_upload = RideUpload.new
  end

  # GET /admin/ride_zones/ca-25/ride_uploads/1/edit
  def edit
  end

  # POST /admin/ride_zones/ca-25/ride_uploads
  def create
    @ride_upload = RideUpload.new(ride_upload_params)
    @ride_upload.user = current_user
    @ride_upload.ride_zone = @ride_zone
    
    if @ride_upload.total_rows > 1000
      redirect_to admin_ride_zone_ride_uploads_path(@ride_zone.slug), notice: 'CSVs can not be more than 1000 lines long.'
    else  
      
      # TODO: Should a radius check be added to PotentialRide, and should it be made geolocatable?
      if @ride_upload.pending!
        total_rows = 0
        successful_rows = 0
        CSV.parse(@ride_upload.csv.download, headers: true) do |row|
          total_rows += 1
          potential_ride = PotentialRide.new(ride_zone: @ride_zone, ride_upload: @ride_upload, status: :pending, row_number: total_rows)
          if potential_ride.populate_from_csv_row(row)
            successful_rows += 1 
          else
            potential_ride.fail_because("Failed to populate csv row #{row_number}")
          end
          potential_ride.save
        end
      
        @ride_upload.total_rows = total_rows
        @ride_upload.successful_rows = successful_rows
        @ride_upload.queued!
        @ride_upload.save
      
        redirect_to admin_ride_zone_ride_upload_path(@ride_zone.slug, @ride_upload), notice: 'Ride upload was successfully created, you still need to schedule the rides.'
      else
        render :new
      end
    end
  end
  
  # POST /admin/ride_zones/ca-25/ride_uploads/1
  # Go through all the PotentialRides associated with this RideUpload
  # If any can't be processed, fail the whole thing and don't process any
  # If all look like they can be scheduled, do so
  def schedule
    fail_count = 0
    
    # TODO: queue a single large job to create rides from potential_rides. Needs to be a single big
    # job, one per ride_upload, so that it can change the status of the ride_upload at the end.
    # - get rid of fail count, instead rely on counting PotentialRides in RideUpload with :failed status
    # - Move code below into a job: ConvertPotentialRidesJob
    # rails generate job convert_potential_rides_job --queue convert_potential_rides
    # ConvertPotentialRidesJob.perform_later potential_job
    # - block of code at end
    @ride_upload.potential_rides.each do |potential_ride|
      
      if user = User.find_from_potential_ride( potential_ride )
        if user.active_or_open_rides?
          potential_ride.fail_because("User already has an active or open ride"); fail_count += 1
          next
        else
          begin
            ride = Ride.create_from_potential_ride( potential_ride, user )
          rescue ActiveRecord::RecordInvalid => e
            potential_ride.fail_because("Found user, but record was invalid: #{e}"); fail_count += 1
          rescue Exception => e
            potential_ride.fail_because("Found user, failed, generally: #{e}"); fail_count += 1
          end
        end
      else
        begin
          user = User.create_from_potential_ride( potential_ride )
          potential_ride.voter = user
        rescue ActiveRecord::RecordInvalid => e
          potential_ride.fail_because("Could not create user: #{e}"); fail_count += 1
        end
        
        if potential_ride.voter.present?
          begin
            ride = Ride.create_from_potential_ride( potential_ride )
          rescue Exception => e
            potential_ride.fail_because("Created User, could not create Ride: #{e}"); fail_count += 1
          end
        end
      end
      
      if ride.present?
        Conversation.create_from_ride(ride, thanks_msg(ride))
        UserMailer.welcome_email_voter_ride(user, ride).deliver_later unless user.email&.include? "example.com"
      end
      
    end
    
    if fail_count == 0
      @ride_upload.complete!
      notice = "Rides were successfully scheduled."
    elsif fail_count < @ride_upload.total_rows
      @ride_upload.complete_with_failures!
      notice = "Some or all rides failed to schedule, please check logs or contact DtV help."
    else
      @ride_upload.failed!
      notice = "Scheduling rides failed."
    end

    redirect_to admin_ride_zone_ride_upload_path, notice: notice
  end

  # PATCH/PUT /admin/ride_zones/ca-25/ride_uploads/1
  def update
    if @ride_upload.update(ride_upload_params)
      redirect_to @ride_upload, notice: 'Ride upload was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/ride_zones/ca-25/ride_uploads/1
  def destroy
    @ride_upload.destroy
    redirect_to ride_uploads_url, notice: 'Ride upload was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ride_upload(param = :id)
      @ride_upload = RideUpload.find_by_id(params[param]) || RideUpload.find_by_slug(params[param])
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_ride_zone(param = :ride_zone_id)
      @ride_zone = RideZone.find_by_id(params[param]) || RideZone.find_by_slug(params[param])
      raise ActiveRecord::RecordNotFound.new unless @ride_zone
    end

    # Only allow a trusted parameter "white list" through.
    def ride_upload_params
      params.require(:ride_upload).permit(:user_id, :ride_zone_id, :name, :description, :csv, :status, :csv_hash)
    end
end

app/views/admin/ride_uploads/_form.html.haml
= form_for( @ride_upload, url: admin_ride_zone_ride_uploads_path(@ride_zone)) do |f|
  - if @ride_upload.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ride_upload.errors.count, "error")} prohibited this ride_upload from being saved:"
      %ul
        - @ride_upload.errors.full_messages.each do |message|
          %li= message

  .col-sm-8.field
    = f.label :name
    .small{style: "margin-top: -10px;"}
      To identify the file, ie, "Precinct 8," "October canvassing," etc.
    = f.text_field :name, autofocus: true, class: 'form-control'
    
  .col-sm-8.field
    = f.label :description
    = f.text_area :description, class: 'form-control'
    
  .col-sm-8.field
    = f.label :csv, "CSV file"
    = f.file_field :csv, class: 'form-control'
    
    
  .col-sm-8.actions
    = f.submit t(:save), class: 'btn btn-primary', disabled: true, disable_with: "#{t(:saving)}…"
    
:javascript
  $(document).ready(
    function(){
      $('input:file').change(
        function(){
          if ($(this).val()) {
            $('input:submit').attr('disabled',false);
          } 
        }
      );
    }
  );

app/views/admin/ride_uploads/edit.html.haml
%h1 Editing scheduled_ride_upload

= render 'form'

= link_to 'Show', @scheduled_ride_upload
\|
= link_to 'Back', scheduled_ride_uploads_path

app/views/admin/ride_uploads/index.html.haml
:css
  td { padding-right: 30px; }
  th { padding-right: 30px; font-size: 20px; }
  .pending { background-color: red;}

%h6
  = @ride_zone.name
%h3{style: "margin-top: 0;"}
  Scheduled Ride Uploads

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Date
      %th Rows
      %th PRides
      %th Status
      %th{style: "padding-right: 0;"}

  %tbody
    - @ride_uploads.each do |ride_upload|
      %tr
        %td
          = link_to ride_upload.name, admin_ride_zone_ride_upload_path(@ride_zone.slug, ride_upload)
        %td
          = ride_upload.description
        %td
          = ride_upload.created_at.strftime("%m/%d/%Y")
        %td
          = ride_upload.total_rows
        %td
          = ride_upload.potential_rides.count
          
        %td{class: ride_upload.status}
          = ride_upload.status
          
        %td{style: "padding-right: 0;"}
          = link_to 'Download', rails_blob_path(ride_upload.csv, disposition: "attachment")
          
          -#= link_to 'Edit', edit_ride_upload_path(ride_upload)
          -#= link_to 'Destroy', ride_upload, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Upload', new_admin_ride_zone_ride_upload_path(@ride_zone.slug), class: 'btn btn-primary'

app/views/admin/ride_uploads/new.html.haml
:css
  h1 { font-size: 22px;}

%h1
  Scheduled Rides Upload
  
%p
  Use this form to upload a file of voters to create pre-scheduled election-day rides in Drive the Vote.

%p
  The spreadsheet must be saved as a correctly formatted CSV (<a href="https://en.wikipedia.org/wiki/Comma-separated_values">comma-separated value</a>) file--if your Drive the Vote contact hasn't provided you with a template, please reach out to them, or email <a href="mailto:hello@drive.com">hello@drive.vote</a>.

%p
  Upon upload Drive the Vote will validate your file to make sure every row can be converted into a ride. It will tell you if any need to be fixed or removed.

%p
  Once everything validates, and you confirm it looks good, Drive the Vote will schedule the rides. Then they'll be visible in the 'Rides' section of the dispatcher app.

= render 'form'

-#= link_to 'Back', admin_ride_zone_ride_uploads_path(@ride_zone)

app/views/admin/ride_uploads/show.html.haml
:css
  h1 { font-size: 20px; }
  .queued{background-color:orange; padding: 1px;}
  .pr {font-size: 13px;}
  .pending {margin-right: 5px; background-color:yellow; padding: 1px;}
  .fail {margin-right: 5px; background-color:red; padding: 1px;}
  .no_ride {margin-right: 5px; background-color:orange; padding: 1px;}
  .yes {margin-right: 5px; background-color:green; color: white; padding: 1px;}
  .desc {margin-top: 0; }

%p#notice
  = notice

%h2
  #{@ride_upload.name}
%div{style: "margin-top: -10px;"}
  Uploaded #{@ride_upload.created_at.strftime("%B %d, %Y")} by #{@ride_upload.user.name}

- if @ride_upload.description.present?
  .desc
    = @ride_upload.description
    
%p
  %i Status:
  %b.queued
    = @ride_upload.status
%div{style: "margin-top: -20px;"}
  - if @ride_upload.csv.present?
    = link_to 'Download file', rails_blob_path(@ride_upload.csv), target: "_blank" 
  - else
    none
    
%p{style: 'margin: 20px 0 5px 0;'}
  %i
    Potential Rides:
- @ride_upload.potential_rides.each do |pr|
  .pr
    - if pr.ride.blank?
      - if pr.failed?
        %span.fail
          &nbsp;&nbsp;
      - elsif pr.pending?
        %span.pending
          &nbsp;&nbsp;
      - else
        %span.no_ride
          &nbsp;&nbsp;
    - else
      %span.yes
        &nbsp;&nbsp;
    #{pr.name}, #{pr.from_address}, #{pr.from_city}
    - if pr.notes.present?
      [#{pr.notes}]
    

  
- if @ride_upload.queued?
  %p
    %br
    = link_to 'Schedule', schedule_admin_ride_zone_ride_upload_path(@ride_upload.ride_zone, @ride_upload), class: 'btn btn-primary'
    
- if @failed_potential_rides.present?
  %h5
    Failed potential rides from upload:
  %ul
    - @failed_potential_rides.each do |fpr|
      %li
        #{fpr.name} (#{fpr.notes})
    
%hr
%p
  = link_to 'Ride Upload Index', admin_ride_zone_ride_uploads_path(@ride_zone.slug)