config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  devise_scope :user do
    get '/volunteer/:id', :to => 'users/registrations#new', :as => 'volunteer_to_drive_for_zone'
    get '/volunteer_to_drive/:id', to: redirect("/volunteer/%{id}")
    get '/volunteer_to_drive', :to => 'users/registrations#new', :as => 'volunteer_to_drive'
    get "/users/sign_out" => "devise/sessions#destroy", :as => :get_destroy_user_session
  end

  # https://blog.heroku.com/real_time_rails_implementing_websockets_in_rails_5_with_action_cable
  # NOTE: to re-enable you also need to uncomment ./channels in application.js,
  # and the code in /channels/messages.js
  # and the meta tag in application.html.haml
  # and lined in development.rb and production.rb
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'home#index'

  match '/confirm' => 'home#confirm', via: :get, as: :confirm
  match '/about' => 'home#about', via: :get, as: :about
  match '/code_of_conduct' => 'home#code_of_conduct', via: :get, as: :code_of_conduct
  match '/terms_of_service' => 'home#terms_of_service', via: :get, as: :terms_of_service
  match '/privacy' => 'home#privacy', via: :get, as: :privacy

  get 'dispatch/:ride_zone_id/ride/:ride_id/edit' => 'dispatch#edit_ride', as: 'dispatch_edit_ride'
  resources :dispatch, only: [:show] do
    member do
      get 'messages' => 'dispatch#messages'
      get 'ride_pane' => 'dispatch#ride_pane'
      get 'drivers' => 'dispatch#drivers'
      get 'rides' => 'dispatch#rides'
      get 'flyer' => 'dispatch#flyer'
      get 'map' => 'dispatch#map'
    end
  end

  resources :driving do
    collection do
      get 'demo' => 'driving#demo'
      get 'status' => 'driving#status'
      post 'location' => 'driving#update_location'
      post 'available' => 'driving#available'
      post 'unavailable' => 'driving#unavailable'
      post 'accept_ride' => 'driving#accept_ride'
      post 'unaccept_ride' => 'driving#unaccept_ride'
      post 'pickup_ride' => 'driving#pickup_ride'
      post 'complete_ride' => 'driving#complete_ride'
      post 'cancel_ride' => 'driving#cancel_ride'
      get 'waiting_rides' => 'driving#waiting_rides'
      get 'ridezone_stats' => 'driving#ridezone_stats'
    end
  end

  get 'ride/:ride_zone_id' => 'rides#new', as: 'get_a_ride'
  get 'get_a_ride/:ride_zone_id', to: redirect("/ride/%{ride_zone_id}")
  get 'conseguir_un_paseo/:ride_zone_id' => 'rides#new'

  resources :rides, only: [:create, :edit, :update]

  resources :users do
    get :confirm, on: :member
  end

  namespace :api do
    namespace :v1, path: '1' do
      post 'twilio/sms' => 'twilio#sms'
      post 'twilio/voice' => 'twilio#voice'
      get 'places/search' => 'places#search'

      resources :conversations, only: [:show, :update] do
        member do
          post 'messages' => 'conversations#create_message'
          post 'close' => 'conversations#close'
          post 'rides' => 'conversations#create_ride'
          post 'update_attribute' => 'conversations#update_attribute'
          post 'remove_help_needed' => 'conversations#remove_help_needed'
        end
      end

      resources :rides, only: [:update_attribute] do
        collection do
          if ENV['DTV_IS_WORKER'] == 'TRUE' || Rails.env.test?
            post 'confirm_scheduled' => 'rides#confirm_scheduled'
          end
        end
        member do
          post 'update_attribute' => 'rides#update_attribute'
        end
      end

      resources :ride_zones do
        member do
          post 'assign_ride' => 'ride_zones#assign_ride'
          get 'conversations' => 'ride_zones#conversations'
          post 'conversations' => 'ride_zones#create_conversation'
          get 'drivers' => 'ride_zones#drivers'
          get 'rides' => 'ride_zones#rides'
          post 'rides' => 'ride_zones#create_ride'
          post 'change_role'
        end
      end
    end
  end

  get '/admin', to: redirect('/admin/ride_zones')
  match '/admin/voters' => 'admin/users#voters', via: :get
  namespace :admin do
    resources :conversations, only: [:index, :show] do
      member do
        # get 'messages' => 'conversations#messages'
        # get 'ride_pane' => 'conversations#ride_pane'
        post 'close' => 'conversations#close'
        post 'blacklist_voter_phone' => 'conversations#blacklist_voter_phone'
        post 'unblacklist_voter_phone' => 'conversations#unblacklist_voter_phone'
      end
    end
    resources :drivers, only: [:index] do
      member do
        post 'toggle_available'
      end
    end
    resources :metrics, only: [:index]
    resources :rides
    
    resources :ride_zones, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      member do
        get 'drivers'
        post 'add_role'
        post 'change_role'
        delete 'remove_role'
      end
      resources :ride_uploads do
        member do
          get 'schedule'
        end
      end
    end
    
    resources :simulations, only: [:index] do
      collection do
        post 'start_new' => 'simulations#start_new'
        post 'clear_all_data' => 'simulations#clear_all_data'
      end
      member do
        post 'stop' => 'simulations#stop'
        delete 'delete' => 'simulations#delete'
      end
    end
    resource :site, only: [:show, :edit, :update]
    resources :users, only: [:show, :edit, :update, :index, :destroy] do
      member do
        post 'qa_clear' => 'users#qa_clear'
      end
    end
  end

end

app/controllers/dispatch_controller.rb
class DispatchController < ApplicationController
  include RideZoneParams
  include RideParams
  include AccessMethods

  before_action :set_ride_zone, except: [:messages, :ride_pane, :edit_ride]
  before_action :set_conversation, only: [:messages, :ride_pane]
  before_action :require_zone_dispatch
  before_action :get_driver_count, except: [:messages, :ride_pane, :edit_ride]

  def show
    @fluid = true
  end

  def messages
    render partial: 'messages'
  end

  def ride_pane
    ride = @conversation.ride
    @zone_driver_count = @conversation.ride_zone.drivers.count
    @available_drivers = @conversation.ride_zone.available_drivers
    @available_drivers_with_distance = @available_drivers.map  do |d|
      [d, ride ? ride.distance_to_point(d.latitude, d.longitude) : 0]
    end.sort do |pair1, pair2|
      pair1[1] <=> pair2[1]
    end

    if ride.present?
      @action =  'Edit'
      @obj = ride
    else # create ride
      @action =  'Create'
      @obj = @conversation
    end

    @pickup_at = @obj.try(:pickup_at).try(:in_time_zone, @obj.ride_zone.time_zone) || ""
    render partial: 'dispatch/form'
  end

  def drivers
    @sort = params[:sort]&.to_sym || :name
    @drivers = @ride_zone.drivers.order(@sort)
    if current_user.has_role?(:admin, @ride_zone) || current_user.has_role?(:admin)
      @unassigned_drivers = @ride_zone.unassigned_drivers.order(@sort)
      @nearby_drivers = @ride_zone.nearby_unassigned_drivers.order(@sort)
    end
    respond_to do |format|
      format.html
      format.csv do
        if current_user.has_role?(:admin, @ride_zone) || current_user.has_role?(:admin)
          all_drivers = @ride_zone.unassigned_drivers.or( @ride_zone.drivers ) #.merge(@ride_zone.nearby_unassigned_drivers)
          send_data all_drivers.to_csv({headers: true}, @ride_zone.time_zone), filename: "drivers-#{Date.today}.csv"
        else
          redirect_to root_path
        end
      end
    end
  end

  def rides
    @rides = Ride.where(ride_zone: @ride_zone).upcoming.order(:pickup_at)
    render "dispatch/rides/index"
  end

  def edit_ride
    @ride = Ride.find(params[:ride_id])
    @ride.from_city_state = [@ride.from_city, @ride.from_state].reject {|s| s.blank?}.compact.join(', ')
    @ride.to_city_state = [@ride.to_city, @ride.to_state].reject {|s| s.blank?}.compact.join(', ')

    I18n.locale = @ride.voter.locale
    @ride_zone = @ride.ride_zone
    render "dispatch/rides/edit"
  end

  def flyer
    respond_to do |format|
      format.pdf do
        pdf = RideZonePdf.new(@ride_zone, view_context)
        send_data pdf.render, filename:
        "ride_zone_#{@ride_zone.slug}.pdf",
        disposition: "inline",
        type: "application/pdf"
      end
    end
  end

  def map
  end

  private

  def get_driver_count
    @driver_count = @ride_zone.drivers.count(:all)
    @active_driver_count = @ride_zone.on_duty_drivers.count
  end

  def set_conversation
    @conversation = Conversation.find(params[:id])
    @ride_zone = @conversation.ride_zone
  end
end

app/views/dispatch/_form.html.haml
.modal-ride-status
  - if @obj.is_a?(Conversation)
    Active conversation
  - else
    Ride scheduled
- if @obj.is_a?(Ride) && @obj.conversation.status == 'help_needed' && @obj.conversation.lifecycle == 'info_complete'
  = button_tag 'Remove "Help Needed" alert', class: 'btn btn-info btn-xs remove-help-needed'

- url = send("update_attribute_api_v1_#{@obj.class.name.downcase}_path", @obj)

%table
  %tr
    %td.conv-label
      FROM
    %td.conv-field
      %div
        %a.to_from{href: '#', id:"from_address", 'data-type':"text", 'data-pk':"#{@obj.send(:id)}", 'data-url':"#{url}", 'data-title':"From address"}
          = @obj.send(:from_address)
      %div{style: "padding-bottom: 20px;"}
        %a.to_from{href: '#', id:"from_city", 'data-type':"text", 'data-pk':"#{@obj.send(:id)}", 'data-url':"#{url}", 'data-title':"From city"}
          = @obj.send(:from_city)

  %tr
    %td.conv-label
      TO
    %td.conv-field
      %div
        %a.to_from{href: '#', id:"to_address", 'data-type':"text", 'data-pk':"#{@obj.send(:id)}", 'data-url':"#{url}", 'data-title':"To address"}
          = @obj.send(:to_address)
      %div{style: "padding-bottom: 20px;"}
        %a.to_from{href: '#', id:"to_city", 'data-type':"text", 'data-pk':"#{@obj.send(:id)}", 'data-url':"#{url}", 'data-title':"To city"}
          = @obj.send(:to_city)

  %tr
    %td.conv-label
      PICKUP TIME
    %td.conv-field#pickup_at
      %input{type: 'text', class: 'flatpickr'}

  %tr
    %td.conv-label
      EXTRA PASSENGERS
    %td.conv-field
      %a.to_from{href: '#', id:"additional_passengers", 'data-type':"text", 'data-pk':"#{@obj.send(:id)}", 'data-url':"#{url}", 'data-title':"Additional Passengers"}
        = @obj.send(:additional_passengers) || 0

  %tr
    %td.conv-label
      SPECIAL REQ
    %td.conv-field
      %a.to_from{href: '#', id:"special_requests", 'data-type':"text", 'data-pk':"#{@obj.send(:id)}", 'data-url':"#{url}", 'data-title':"Special Requests"}
        = @obj.send(:special_requests)

  - if @obj.class == Conversation
    - @show_create_ride = @obj.has_fields_for_ride?

    %tr.show_create_ride{style: "display: #{@show_create_ride ? 'table-row' : 'none'};"}
      %td.conv-label{colspan: '2'}
        %a.create_ride{href: '#', class: 'btn btn-sm btn-info', style: 'margin-top: 30px;'}
          CREATE RIDE
        %br
        %small
          Once you've created a ride it becomes visible to drivers. If you want to specify a driver, reload the conversation after clicking 'Create Ride'.

    %tr.hide_create_ride{style: "display: #{@show_create_ride ? 'none' : 'table-row'};"}
      %td{colspan: '2'}
        %button{style: "margin: 20px 10px 0 0;"}
          'From' address and pickup time need to be filled in before a ride request can be made available to drivers.


  - if @obj.class == Ride
    %tr
      %td.conv-label
        CURRENT DRIVER
      %td.conv-field.current-driver
        - if @obj.driver.present?
          = @obj.driver.name
        - else
          %i
            Unassigned

    %tr
      %td.conv-label
        SET DRIVER
      %td.conv-field
        - if @zone_driver_count == 0
          %i
            There are no drivers assigned to this zone.
        - else
          - if @available_drivers_with_distance.present?
            %select{id: 'driver_select'}
              %option
                Select driver:
              - @available_drivers_with_distance.each do |driver|
                %option{value: driver[0].id}
                  (#{driver[1].round(1)} mi) #{driver[0].name}

          - else
            %i
              No nearby drivers are currently available.

  :javascript
    $( function() {
      dispatchController.attachInlineEditables();

      // only pertains to conversations
      dispatchController.attachRideCreate(#{@obj.id});

      // only pertains to Rides
      dispatchController.attachDriverSelect(#{@obj.ride_zone_id}, #{@obj.id}, "#driver_select", "#{@action.downcase}");

      $(".flatpickr").flatpickr({
        enableTime: true,
        minuteIncrement: 5,
        dateFormat: "F j, h:iK",
        defaultDate: "#{@pickup_at}",
        onClose: function(dateObj, dateStr, instance){
          $.post( "#{url}", {name: 'pickup_at', value: dateStr}, function(data) {
            $('#pickup_at').addClass('item-highlight');
            dispatchController.checkToggleRideCreate(data);
          }).fail(function() {
            humane.log ('There was a problem setting the date.');
          });
        }
      });
    });

  -if @obj.is_a?(Ride)
    :javascript
      $( function() {
        $(".remove-help-needed").click(function(e) {
          e.preventDefault();
          $.post( "#{remove_help_needed_api_v1_conversation_path(@obj.conversation)}", function(data) {
            $('.remove-help-needed').hide();
          }).fail(function() {
            alert('Unable to remove the help needed alert');
          });
        })
      });

app/views/dispatch/_init.js.erb
var dispatchMapController;
var dispatchController;

var gmap = new Mapp(document.getElementById('dispatch-map'), onMapLoaded,
                   {'google_api_key': "<%= ENV['GOOGLE_API_KEY'] %>",
                    lat: <%= @ride_zone.latitude %>, lon: <%= @ride_zone.longitude %>, zoom: 13});

function onMapLoaded(map) {
  dispatchMapController = new DispatchMapController(map);
  dispatchController = new DispatchController(<%= @ride_zone.id %>, dispatchMapController, <%= @ride_zone.bot_disabled %>);
  dispatchController.init();
}

app/views/dispatch/_map_key.html.haml
%table.key{style: 'margin-bottom: 30px;'}
  %thead
    %tr
      %th{colspan: 2} Voter
      %th{colspan: 2} Driver
  %tr
    %td.key-pin-cell= image_tag "rider-needs-driver.svg", class: 'key-pin-rider-img'
    %td.key-label     Needs a driver
    %td.key-pin-cell= image_tag "driver-available.svg", class: 'key-pin-driver-img'
    %td.key-label     Available
    %td{rowspan: 3, style: 'text-align: center'}
      #dispatch-map-controls{style: 'margin-bottom: 1em; display:none'}
        %button.btn.btn-success.btn-xs#show-all-pins
          Show all pins
        %br
        %span#out-of-bounds-message{style: 'color: #666; font-size: 13px;'}

  %tr
    %td.key-pin-cell= image_tag "rider-assignment-overdue.svg", class: 'key-pin-rider-img'
    %td.key-label     Overdue assignment
    %td.key-pin-cell= image_tag "driver-assigned.svg", class: 'key-pin-driver-img'
    %td.key-label     Assigned
  %tr
    %td.key-pin-cell= image_tag "rider-waiting-for-pickup.svg", class: 'key-pin-rider-img'
    %td.key-label     Waiting for pickup
    %td.key-pin-cell= image_tag "driver-driving.svg", class: 'key-pin-driver-img'
    %td.key-label     Driving
  %tr
    %td.key-pin-cell= image_tag "rider-pickup-overdue.svg", class: 'key-pin-rider-img'
    %td.key-label     Pickup overdue
    %td.key-pin-cell= image_tag "driver-overdue.svg", class: 'key-pin-driver-img'
    %td.key-label     Completion overdue

app/views/dispatch/_messages.html.haml
-# Mashing haml around with js is not the way to do this.

- if (@conversation&.user&.phone_number_normalized.present? && @conversation.messages.any?)
  .messages
    - @conversation.messages.order('created_at asc').each do |message|
      - if @conversation.user.phone_number_normalized.present?
        .message{style: "text-align: #{(message.sent_by == 'Voter') ? 'left' : 'right'}"}

        %code
          %span.msg-epoch
            = message.created_at.to_i
          , #{message.sent_by}
        .msg-body
          = message.body

-# just to make the javascript below a little easier to read
- if @conversation&.ride&.status == 'canceled'
  - close_button = ''
- else
  - close_button = j( link_to "Archive Ride", '#', class: 'btn btn-xs btn-warning archive-convo' )

- if @conversation.voter_phone_blacklisted?
  - block_button = j( link_to 'Unblock #', '#', class: 'btn btn-default btn-xs unblock-convo' )
- else
  - block_button = j( link_to 'Block #', '#', class: 'btn btn-danger btn-xs block-convo' )


- if @conversation.user.name.include?('via sms')
  - title = @conversation.from_phone.phony_formatted(normalize: :US, spaces: '-')
- else
  - title = "#{h @conversation.user.name} <span>#{@conversation.user.phone_number_normalized.present? ? @conversation.user.phone_number.phony_formatted(normalize: :US, spaces: '-') : ''}</span>".html_safe

- if @conversation&.user&.phone_number_normalized.present?
  - show_messages = "show();"
  - no_phone = "hide();"
- else
  - show_messages = "hide();"
  - no_phone = "show();"

:javascript
  $('#conversation-messages').#{show_messages}
  $('.msg-reply').#{show_messages}
  $('.no-phone').#{no_phone}

  // now that we have the conversation object, populate the modal header
  $('#conv-modal-title').html( "#{title}" );

  // convert epoch times to human-readable local times
  $('.msg-epoch').each(function(index) {
    $(this).text( strftime('%l:%M%P', new Date( $(this).text()*1000)) );
  });

  $('#archive-btn').html("<span style='font-weight: normal;'>#{close_button}</span> \
  <span style='font-weight: normal;'>#{block_button}</span> \
  ")

  $('.archive-convo').click(function(e) {
    if (confirm("Are you sure? This will end the conversation and cancel the ride no matter what state it is in, and you will not be able to reopen or reassign it. This is a complete cancellation of this voter's ride" )) {
      $.post( '/api/1/conversations/#{@conversation.id}/close', function(responseData, status, xhr) {
         $('#conv-modal').modal('hide')
        humane.log ('Conversation archived');
      }).fail(function() {
        humane.log ('Unable to archive conversation');
      });
    }
    e.preventDefault();
  });

  $('.unblock-convo').click(function(e) {
    if (confirm("Are you sure you want to unblock phone number #{@conversation.from_phone}?" )) {
      $.post( "#{unblacklist_voter_phone_admin_conversation_path(@conversation)}", function(responseData, status, xhr) {
        humane.log ('number unblocked');
      }).fail(function() {
        humane.log ('Unable to unblock number');
      });
    }
    e.preventDefault();
  });

  $('.block-convo').click(function(e) {
    if (confirm("Are you sure you want to permanently block this phone number, #{@conversation.from_phone}?" )) {
      $.post( "#{blacklist_voter_phone_admin_conversation_path(@conversation)}", function(responseData, status, xhr) {
        humane.log ('number blocked');
      }).fail(function() {
        humane.log ('Unable to block number');
      });
    }
    e.preventDefault();
  });

app/views/dispatch/_modal.html.haml
-# Most of the content that will fill below gets jacked in by the javascript in _messages.html.haml
-# since it's only after a ride has been clicked on that we'll know what belongs here.

.modal.fade.modal-body#conv-modal{"aria-labelledby" => "conv-modal-title", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-lg{:role => "document"}
    .modal-content
      .modal-header
        %button.close{type: 'button', 'data-dismiss': 'modal', 'aria-label': 'Close'}
          %span{'aria-hidden': 'true'} x

        #conv-modal-title.pull-left
        #archive-btn

      .modal-body
        %table{style: 'width: 850px;'}
          %tr
            %td{style: 'width: 500px;'}
              - if @ride
                #ride_info
              - else
                #conversation-form

            %td{style: 'width: 340px;'}
              #conversation-messages
              .msg-reply
                #msg-input{ contenteditable: true}
                = button_tag 'Send', id: 'msg-submit', class: 'btn btn-send btn-primary btn-xs pull-right'
              %p.no-phone
                No number on record for this voter.
                
          %tr
            %td
            %td
              #msg-error-display

app/views/dispatch/_nav.html.haml
%h3.dispatch
  = @ride_zone.name

  %span.dispatch-links{style: 'border: 0px solid red;'}
    = @ride_zone.phone_number.phony_formatted(normalize: :US, spaces: '-')
    &nbsp; · &nbsp;


    = (action_name == 'show') ? "<b>Dashboard</b>".html_safe : link_to('Dashboard', dispatch_path(@ride_zone.slug))
    &nbsp; · &nbsp;

    = (action_name == 'drivers') ? "<b>Drivers</b> (#{@active_driver_count}/#{@driver_count})".html_safe : link_to("Drivers (#{@active_driver_count}/#{@driver_count})", drivers_dispatch_path(@ride_zone.slug))
    &nbsp; · &nbsp;
    
    = (action_name == 'rides') ? "<b>Rides</b>".html_safe : link_to("Rides", rides_dispatch_path(@ride_zone.slug))
    
    &nbsp; · &nbsp;

    = (action_name == 'map') ? "<b>Large Map</b>".html_safe : link_to('Large map', map_dispatch_path(@ride_zone.slug))
    &nbsp; · &nbsp;

    = link_to 'Schedule a ride', get_a_ride_path(@ride_zone.slug), target: '_blank'
    &nbsp; · &nbsp;

    = link_to 'Poll finder', 'https://gttp.votinginfoproject.org/', target: '_blank'
    &nbsp; · &nbsp;

    %a.dispatch-xtras.glyphicon.glyphicon-cog{ 'data-toggle': "popover" }

:javascript
  $(function () {
    var content = "#{j( link_to 'Driver volunteer form', volunteer_to_drive_for_zone_path(@ride_zone.slug), target: '_blank')}";

    content += "<div class='disp-extras'>";
    content += "#{j( link_to 'Driver app', driving_index_path, target: '_blank')}";
    content += "</div>";
    
    content += "<div class='disp-extras'>";
    content += "#{j( link_to @ride_zone.bot_disabled ? 'Enable Bot' : 'Disable Bot', '', onclick: 'dispatchController.toggleBotDisabled(); return false;', class: 'disp-bot-disable') }";
    content += "</div>";

    $('.dispatch-xtras').popover({
      placement: 'bottom',
      html: true,
      content: content})
  })

app/views/dispatch/drivers.html.haml
:css
  h2 { font-size: 20px; font-weight: bold; color: #999; margin: 50px 0 -20px 0;}
  td { border: 0px solid grey;}
  .created_at {color: grey;}

= render partial: 'dispatch/nav'

%div{style: "margin: 20px 0 0 15px;"}
  Sort &nbsp;
  %select.sort
    %option
      name
    - if @sort.to_s == 'created_at'
      %option{ selected: true }
        created_at
    - else
      %option
        created_at

  - if current_user.has_role?(:admin, @ride_zone) || current_user.has_role?(:admin)
    &nbsp;&nbsp; · &nbsp;&nbsp;
    = link_to 'Download .csv', drivers_dispatch_path(format: 'csv'), class: 'btn btn-info btn-xs'

  &nbsp;&nbsp; · &nbsp;&nbsp;
  -# &#128308; = red_circle, &#128309; = blue_circle, &#128661; = taxi
  &#128309; = on duty &nbsp;&nbsp;&nbsp;&nbsp; &#128308; = off duty &nbsp;&nbsp;&nbsp; &#128661; = mid-ride

:javascript
  $('.sort').change(function() {
    window.location.href = window.location.pathname + "?sort=" + $('.sort option:selected').val();;
  });

  $(document).ready(function() {
    $(".no-off-duty").click(function() {
       alert("You can't take a driver off duty when they are in the middle of a ride.\nAssign a new driver or archive the ride first.");
    });
  });

.col-md-12

  %h2{style: 'margin-top: 20px;'}
    Approved drivers
  %table.table{style: 'margin-top: 40px;'}
    %tr
      %td
      %td
        email
      %td
        phone
      - if current_user.is_zone_or_super_admin?
        %td
          signed up
      %td
        last active

      - if current_user.is_zone_or_super_admin?
        %td
      %td

    - if @drivers&.size > 0
      - @drivers.each do |driver|
        %tr
          %td
            = driver.name
            != driver.available? ? '&#128309; ' : '&#128308; '
            - if driver.active_ride.present?
              &#128661;
          %td
            = mail_to driver.email
          %td
            = tel_to  driver.phone_number.phony_formatted(normalize: :US, spaces: '-')

          - if current_user.is_zone_or_super_admin?
            %td.created_at
              = driver.created_at.in_time_zone(@ride_zone.time_zone).strftime("%-m/%-d %l:%M%P")
          %td.last_active
            = driver.updated_at.in_time_zone(@ride_zone.time_zone).strftime("%l:%M%P, %-m/%-d")

          - if current_user.is_zone_or_super_admin?
            %td
              = link_to 'demote', change_role_admin_ride_zone_path(@ride_zone, to_role: 'unassigned_driver', driver: driver.id), method: :post
          %td
            - if driver.available?
              -# pause-button emoji
              - if driver.active_ride.present?
                %span.no-off-duty{title: "Cannot take driver off duty mid-ride"}
                  = link_to '⏸️', '#', onClick: "You can't take a driver off duty mid-ride. If you think they just forgot to mark their last ride complete, please call and ask them to do so."
              - else
                = link_to '⏸️', toggle_available_admin_driver_path(id: driver.id), method: :post, title: "Take driver off duty"

    - else
      %tr
        %td{colspan: '3'}
          %i
            None

  - if current_user.has_role?(:admin, @ride_zone) || current_user.has_role?(:admin)
    %h2 Unapproved drivers
    %table.table{style: 'margin-top: 40px;'}
      - if @unassigned_drivers&.size > 0
        - @unassigned_drivers.each do |driver|
          %tr
            %td
              = driver.name
            %td
              = mail_to driver.email
            %td
              = tel_to  driver.phone_number.phony_formatted(normalize: :US, spaces: '-')
            %td.created_at
              = driver.created_at.in_time_zone(@ride_zone.time_zone).strftime("%-m/%-d %l:%M%P")
            %td
              = link_to 'Approve', change_role_admin_ride_zone_path(@ride_zone, to_role: 'driver', driver: driver.id), method: :post
      - else
        %tr
          %td{colspan: '3'}
            %i
              None

    %h2 Nearby unapproved drivers
    %table.table{style: 'margin-top: 40px;'}
      - if @nearby_drivers&.size > 0
        - @nearby_drivers.each do |driver|
          %tr
            %td
              = driver.name
            %td
              = mail_to driver.email
            %td
              = tel_to  driver.phone_number.phony_formatted(normalize: :US, spaces: '-')
            %td.created_at
              = driver.created_at.in_time_zone(@ride_zone.time_zone).strftime("%-m/%-d %l:%M%P")
            %td
              = link_to 'Approve', change_role_admin_ride_zone_path(@ride_zone, to_role: 'driver', driver: driver.id), method: :post

      - else
        %tr
          %td{colspan: '3'}
            %i
              None

app/views/dispatch/map.html.haml
= render partial: 'dispatch/nav'

.col-md-12{style: 'margin-top: 10px;'}
  #dispatch-map

.col-md-12{style: 'margin-top: 10px;'}
  = render partial: 'dispatch/map_key'

:javascript
  #{render partial: 'dispatch/init.js'}