config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  devise_scope :user do
    get '/volunteer/:id', :to => 'users/registrations#new', :as => 'volunteer_to_drive_for_zone'
    get '/volunteer_to_drive/:id', to: redirect("/volunteer/%{id}")
    get '/volunteer_to_drive', :to => 'users/registrations#new', :as => 'volunteer_to_drive'
    get "/users/sign_out" => "devise/sessions#destroy", :as => :get_destroy_user_session
  end

  # https://blog.heroku.com/real_time_rails_implementing_websockets_in_rails_5_with_action_cable
  # NOTE: to re-enable you also need to uncomment ./channels in application.js,
  # and the code in /channels/messages.js
  # and the meta tag in application.html.haml
  # and lined in development.rb and production.rb
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'home#index'

  match '/confirm' => 'home#confirm', via: :get, as: :confirm
  match '/about' => 'home#about', via: :get, as: :about
  match '/code_of_conduct' => 'home#code_of_conduct', via: :get, as: :code_of_conduct
  match '/terms_of_service' => 'home#terms_of_service', via: :get, as: :terms_of_service
  match '/privacy' => 'home#privacy', via: :get, as: :privacy

  get 'dispatch/:ride_zone_id/ride/:ride_id/edit' => 'dispatch#edit_ride', as: 'dispatch_edit_ride'
  resources :dispatch, only: [:show] do
    member do
      get 'messages' => 'dispatch#messages'
      get 'ride_pane' => 'dispatch#ride_pane'
      get 'drivers' => 'dispatch#drivers'
      get 'rides' => 'dispatch#rides'
      get 'flyer' => 'dispatch#flyer'
      get 'map' => 'dispatch#map'
    end
  end

  resources :driving do
    collection do
      get 'demo' => 'driving#demo'
      get 'status' => 'driving#status'
      post 'location' => 'driving#update_location'
      post 'available' => 'driving#available'
      post 'unavailable' => 'driving#unavailable'
      post 'accept_ride' => 'driving#accept_ride'
      post 'unaccept_ride' => 'driving#unaccept_ride'
      post 'pickup_ride' => 'driving#pickup_ride'
      post 'complete_ride' => 'driving#complete_ride'
      post 'cancel_ride' => 'driving#cancel_ride'
      get 'waiting_rides' => 'driving#waiting_rides'
      get 'ridezone_stats' => 'driving#ridezone_stats'
    end
  end

  get 'ride/:ride_zone_id' => 'rides#new', as: 'get_a_ride'
  get 'get_a_ride/:ride_zone_id', to: redirect("/ride/%{ride_zone_id}")
  get 'conseguir_un_paseo/:ride_zone_id' => 'rides#new'

  resources :rides, only: [:create, :edit, :update]

  resources :users do
    get :confirm, on: :member
  end

  namespace :api do
    namespace :v1, path: '1' do
      post 'twilio/sms' => 'twilio#sms'
      post 'twilio/voice' => 'twilio#voice'
      get 'places/search' => 'places#search'

      resources :conversations, only: [:show, :update] do
        member do
          post 'messages' => 'conversations#create_message'
          post 'close' => 'conversations#close'
          post 'rides' => 'conversations#create_ride'
          post 'update_attribute' => 'conversations#update_attribute'
          post 'remove_help_needed' => 'conversations#remove_help_needed'
        end
      end

      resources :rides, only: [:update_attribute] do
        collection do
          if ENV['DTV_IS_WORKER'] == 'TRUE' || Rails.env.test?
            post 'confirm_scheduled' => 'rides#confirm_scheduled'
          end
        end
        member do
          post 'update_attribute' => 'rides#update_attribute'
        end
      end

      resources :ride_zones do
        member do
          post 'assign_ride' => 'ride_zones#assign_ride'
          get 'conversations' => 'ride_zones#conversations'
          post 'conversations' => 'ride_zones#create_conversation'
          get 'drivers' => 'ride_zones#drivers'
          get 'rides' => 'ride_zones#rides'
          post 'rides' => 'ride_zones#create_ride'
          post 'change_role'
        end
      end
    end
  end

  get '/admin', to: redirect('/admin/ride_zones')
  match '/admin/voters' => 'admin/users#voters', via: :get
  namespace :admin do
    resources :conversations, only: [:index, :show] do
      member do
        # get 'messages' => 'conversations#messages'
        # get 'ride_pane' => 'conversations#ride_pane'
        post 'close' => 'conversations#close'
        post 'blacklist_voter_phone' => 'conversations#blacklist_voter_phone'
        post 'unblacklist_voter_phone' => 'conversations#unblacklist_voter_phone'
      end
    end
    resources :drivers, only: [:index] do
      member do
        post 'toggle_available'
      end
    end
    resources :metrics, only: [:index]
    resources :rides
    
    resources :ride_zones, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      member do
        get 'drivers'
        post 'add_role'
        post 'change_role'
        delete 'remove_role'
      end
      resources :ride_uploads do
        member do
          get 'schedule'
        end
      end
    end
    
    resources :simulations, only: [:index] do
      collection do
        post 'start_new' => 'simulations#start_new'
        post 'clear_all_data' => 'simulations#clear_all_data'
      end
      member do
        post 'stop' => 'simulations#stop'
        delete 'delete' => 'simulations#delete'
      end
    end
    resource :site, only: [:show, :edit, :update]
    resources :users, only: [:show, :edit, :update, :index, :destroy] do
      member do
        post 'qa_clear' => 'users#qa_clear'
      end
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminApplicationController
  include UserParams

  before_action :set_user, only: [:show, :edit, :update, :destroy, :qa_clear]

  USER_SEARCH = "(lower(users.name) LIKE ?) OR (users.phone_number LIKE ?) OR (users.email LIKE ?) OR (lower(users.city) LIKE ?)".freeze

  def show
    @admin_zones = RideZone.with_user_in_role(@user, :admin)
    @dispatch_zones = RideZone.with_user_in_role(@user, :dispatcher)
    @driving_zones = RideZone.with_user_in_role(@user, :driver)
    @conversations = Conversation.where(user_id: @user.id)
  end

  def index
    page = params[:page] || 1
    per_page = params[:per_page] || 25
    sort = params[:sort] || 'name'
    if params[:q].present?
      @q = params[:q].downcase
      @users = User.where(USER_SEARCH, "%#{@q}%", "%#{@q}%", "%#{@q}%", "%#{@q}%").order("UPPER(#{sort}) DESC").paginate(page: page, per_page: per_page)
    elsif params[:filter].present? && params[:filter].downcase != 'all'
      @users = User.with_role(params[:filter].to_sym, :any).order("#{sort} DESC").paginate(page: page, per_page: per_page)
    else
      @users = User.users.order(Arel.sql("UPPER(#{sort}) ASC")).paginate(page: page, per_page: per_page)
    end
  end

  def voters
    page = params[:page] || 1
    per_page = params[:per_page] || 25
    sort = params[:sort] || 'users.name'
    if params[:q].present?
      @q = params[:q].downcase
      @users = User.voters.where(USER_SEARCH, "%#{@q}%", "%#{@q}%", "%#{@q}%", "%#{@q}%").order("#{sort} DESC").paginate(page: page, per_page: per_page)
    else
      @users = User.voters.order(:name).paginate(page: page, per_page: per_page)
    end
    render template: 'admin/users/voters'
  end

  def edit
    @user.superadmin = @user.has_role?(:admin)
    @zones_driving_for = RideZone.with_user_in_role(@user, :driver)
    @zones_dispatching_for = RideZone.with_user_in_role(@user, :dispatcher)
  end

  def qa_clear
    @user.qa_clear
    flash[:notice] = "Cleared all data for #{@user.name}"
    redirect_back(fallback_location: admin_users_path)
  end

  def destroy
    @user.destroy
    flash[:notice] = "Deleted #{@user.name}"
    redirect_to admin_users_path
  end

  # # PATCH/PUT /users/1
  # # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)

        if @user.superadmin == 'true'
          @user.add_role(:admin)
        else
          @user.remove_role(:admin)
        end

        format.html do
          redirect_to admin_users_path, notice: 'User was successfully updated.', locale: I18n.locale.to_s
        end
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  skip_before_action :require_no_authentication, only: [:new, :create]

  # GET /resource/sign_up
  # GET /volunteer_to_drive
  def new
    resource = build_resource({})

    if request.path.include?('volunteer')

      if params[:id]&.downcase == 'philadelphia'
        flash[:notice] = 'Sorry, no longer accepting volunteers at that location.'
        redirect_to root_path and return
      end

      @volunteer = true
      resource.user_type = 'unassigned_driver'
    end

    if params[:type].present?
      if params[:type] == 'unassigned_driver'
        resource.user_type = params[:type]
      else
        redirect_to root_path and return
      end
    end

    if params[:id].present?
      if @ride_zone = RideZone.find_by_slug(params[:id])
        resource.ride_zone_id = @ride_zone.id
      else
        render layout: false, file: "#{Rails.root}/public/404.html",  status: 404 and return
      end
    end

    respond_with resource
  end

  # POST /resource
  # Overridden so that when people sign up to volunteer, they're not automatically signed in
  def create
    build_resource(sign_up_params)

    unless resource.password.present?
      generated_password = Devise.friendly_token.first(8)
      resource.password = generated_password
    end

    if resource.city_state.present? && resource.city.blank? && resource.state.blank?
      resource.parse_city_state()
    end
    resource.locale = 'en' if resource.locale.blank?
    resource.language = 'en' if resource.language.blank? #todo: consolidate these
    resource.save

    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up

        if resource.ride_zone_id.present?
          @ride_zone = RideZone.find(resource.ride_zone_id)
          UserMailer.welcome_email_driver(resource, @ride_zone).deliver_later
        else
          UserMailer.welcome_email_driver(resource).deliver_later
        end

        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  protected

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    # super(resource)
    if user_signed_in? && current_user.has_role?(:admin)
      admin_users_path
    else
      confirm_path
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super

    if resource.is_only_unassigned_driver?
      sign_out
      flash[:notice] = "Driver application not yet approved, please contact area admin."
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UserParams

  before_action :set_user, only: [:show, :edit, :update]

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    # user_type is put in to the session in OmniauthCallbacksController
    @type = session['user_type']
  end

  def confirm
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { redirect_to root_path }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    session.delete(:user_type)
    is_new_user = @user.phone_number.blank?

    respond_to do |format|
      if @user.update(user_params)

        # different notice if the user was just created
        notice = (is_new_user) ? 'Welcome to Drive the Vote!' : 'User was successfully updated.'

        format.html do
          redirect_to root_path, notice: notice, is_new_user: is_new_user.to_s, locale: I18n.locale.to_s
        end
        format.json { render :show, status: :ok, location: @user }
      else
        @type = session['user_type']

        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/views/admin/users/_form.html.haml
- if @user.errors.any?
  #error_explanation
    %h2
      = pluralize(@user.errors.count, 'error')
      prohibited this user from being saved:

    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg

= form_for [:admin, @user], :role => 'form', :html => {:class => 'form-horizontal'}  do |f|

  .col-sm-8.field
    %i
      To edit driver/dispatcher roles, go to the edit page for that ride zone.

  - if @zones_driving_for.present?
    .col-sm-8.field
      %i
        Driver for:
      - @zones_driving_for.each do |rz|
        %div
          #{rz.name} &nbsp · &nbsp; [#{link_to 'edit', edit_admin_ride_zone_path(rz)}]

  - if @zones_dispatching_for.present?
    .col-sm-8.field
      %i
        Dispatcher for:
      - @zones_dispatching_for.each do |rz|
        %div
          #{rz.name} &nbsp · &nbsp; [#{link_to 'edit', edit_admin_ride_zone_path(rz)}]

  .col-sm-8.field
    = f.label :name, "#{t(:full_name)} *"
    = f.text_field :name, class: 'form-control', autofocus: true, required: 'true', maxlength: 50

  .col-sm-8.field
    = f.label :phone_number, "#{t(:phone_number)}"
    = f.telephone_field :phone_number, class: 'form-control', maxlength: 20

  .col-sm-8.field
    = f.label :email, "Email *"
    = f.text_field :email, class: 'form-control', required: 'true', maxlength: 50

  .col-sm-8.field
    = f.label :address1, t(:address)
    = f.text_field :address1, class: 'form-control', maxlength: 50

  .clearfix

  .col-sm-8.field
    = f.label :city, t(:city)
    = f.text_field :city, class: 'form-control', maxlength: 50

  .col-sm-8.field
    = f.label :state, t(:state)
    = f.text_field :state, class: 'form-control', maxlength: 50

  .col-sm-8.field
    = f.label :zip, t(:zip)
    = f.text_field :zip, class: 'form-control'

  .col-sm-8.field
    Available? &nbsp;
    %label
      = f.radio_button :available, true, :value => true
      &nbsp; Yes &nbsp;&nbsp;&nbsp;

    %label
      = f.radio_button :available, false, :value => false
      &nbsp; No &nbsp;&nbsp;&nbsp;

  .col-sm-8.field{style: "background-color: #ff9999; padding: 0px 10px 10px 10px;"}
    Super admin? &nbsp;
    %label
      = f.radio_button :superadmin, true, :value => true
      &nbsp; Yes &nbsp;&nbsp;&nbsp;

    %label
      = f.radio_button :superadmin, false, :value => false
      &nbsp; No &nbsp;&nbsp;&nbsp;

    %div{style: "font-style:italic; font-size: 14px; margin-top: -8px;"}
      <b>DANGER!</b> Only give super admin to DtV staff, this gives you access to absolutely everything.

  .col-sm-8.field
    = f.submit t(:save), class: 'btn btn-primary', style: 'width: 100%; margin-top: 10px;', disable_with: "#{t(:saving)}…"

    .small{style: 'margin: 10px 0 50px 0;'}
      By saving you are agreeing to the #{link_to t(:terms_of_service), terms_of_service_path, target: '_blank'}.

app/views/admin/users/edit.html.haml
= render 'admin/nav', {active: 'users'}

%h2
  Edit #{link_to @user.name, @user}

= render 'form'

app/views/admin/users/index.html.haml
:css
  #user-filter { margin: 0 0 20px 0;}
  td { font-size: 14px; }

= render 'admin/nav', {active: 'users'}

%h2
  Users

Filter: &nbsp;
%select#user-filter
  - %w{all admin dispatcher}.each do |role|
    %option{value: role, selected: params[:"filter"] == role}
      = role.gsub('_', ' ')

= render partial: "application/admin_search", locals: { page: 'users' }

%table.table-hover.admin
  %thead
    %tr
      %th Name
      %th Email
      %th Created
      %th Location
      %th Roles
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td{style: 'font-size: 16px; max-width: 250px;'}
          = link_to user.name, admin_user_path(user), title: user.id
          %div{style: 'font-size: 12px; margin-top: 0px; color: #999'}
            = user.phone_number.phony_formatted(normalize: :US, spaces: '-')
        %td
          = mail_to user.email, user.email, target: "_blank"
        %td
          = user.created_at.strftime("%-m/%-d, %-H:%M %P")
        %td
          #{[user.city, user.state, user.zip].reject(&:blank?).join(', ')}
        %td
          = user.role_names

        %td{style: "font-size: 12px;"}
          = link_to 'Edit', edit_admin_user_path(user)
          &nbsp; · &nbsp;
          = link_to 'Destroy', admin_user_path(user), :method => :delete, :data => { :confirm => 'Are you sure?' }
          &nbsp; · &nbsp;
          = link_to 'QA Clear', qa_clear_admin_user_path(user), method: :post, data: { :confirm => "This will delete all conversations, rides, and messages for this user. Are you sure that's what you want to do?" }

- if @users.present?
  %nav{'aria-label': 'pagination'}
    = will_paginate @users #, renderer: BootstrapPagination::Rails

:javascript
  $('#user-filter').change(function() {
    window.location.href = "/admin/users/?filter=" + $(this).val();
  });

app/views/admin/users/new.html.haml
%h1 New user

= render 'form'

app/views/admin/users/show.html.haml
= render 'admin/nav', {active: 'users'}

%h1
  = @user.name
  - if current_user.has_role?(:admin)
    &nbsp;
    %small
      = link_to 'Edit', edit_admin_user_path(@user), class: 'btn btn-default'
    &nbsp;
    %small
      = link_to 'QA Clear', qa_clear_admin_user_path(@user), method: :post, class: 'btn btn-default', data: { :confirm => 'Are you sure?' }

= render partial: "users/info"

%p
  DtV Admin?:
  %b=@user.has_role?(:admin)

Zone admin for:
- if @admin_zones.present?
  - @admin_zones.each do |zone|
    %div
      = zone.name

- else
  %div
    %i
      None

%br
Dispatcher for Zones:
- if @dispatch_zones.present?
  - @dispatch_zones.each do |zone|
    %div
      = zone.name
- else
  %div
    %i
      None

%br
Driving for Zones:
- if @driving_zones.present?
  - @driving_zones.each do |zone|
    %div
      = zone.name
- else
  %div
    %i
      None

%h4 Conversations
= render partial: 'admin/conversations/table', locals: {conversations: @conversations, include_show: true}

app/views/admin/users/voters.html.haml
= render 'admin/nav', {active: 'voters'}

%h2
  Voters

= render partial: "application/admin_search", locals: { page: 'voters' }

%table.table-hover.admin
  %thead
    %tr
      %th Name
      %th Created
      %th Location
      %th Ride
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td{style: 'max-width: 250px;'}
          = link_to user.name, admin_user_path(user)
          %div{style: 'font-size: 12px; margin-top: 0px; color: #999'}
            - if user.phone_number.present?
              = user.phone_number.phony_formatted(normalize: :US, spaces: '-')
              <br />
            = mail_to user.email, user.email, target: "_blank"

        %td
          = user.created_at.strftime("%-m/%-d, %-H:%M %P")
        %td
          #{[user.city, user.state, user.zip].reject(&:blank?).join(', ')}
        %td
          - if ride = user.active_ride
            #{ride.pickup_at.strftime("%-m/%-d, %-H:%M %P")} #{ride.status_str}
            = link_to "(edit ride)", admin_ride_path(ride)

        %td{style: "font-size: 13px;"}
          = link_to 'Edit voter', edit_admin_user_path(user)
          &nbsp; · &nbsp;
          = link_to 'Destroy', admin_user_path(user), :method => :delete, :data => { :confirm => 'Are you sure?' }
          &nbsp; · &nbsp;
          = link_to 'QA Clear', qa_clear_admin_user_path(user), method: :post, data: { :confirm => "This will delete all conversations, rides, and messages for this user. Are you sure that's what you want to do?" }

- if @users.present?
  %nav{'aria-label': 'pagination'}
    = will_paginate @users #, renderer: BootstrapPagination::Rails

:javascript
  $('#user-filter').change(function() {
    window.location.href = "/admin/users/?filter=" + $(this).val();
  });